(cl:defpackage assignment_2_2023-srv
  (:use )
  (:export
   "GETDIST"
   "<GETDIST-REQUEST>"
   "GETDIST-REQUEST"
   "<GETDIST-RESPONSE>"
   "GETDIST-RESPONSE"
   "LASTTARGET"
   "<LASTTARGET-REQUEST>"
   "LASTTARGET-REQUEST"
   "<LASTTARGET-RESPONSE>"
   "LASTTARGET-RESPONSE"
  ))

