// Generated by gencpp from file assignment_2_2023/GoalStatus.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_GOALSTATUS_H
#define ASSIGNMENT_2_2023_MESSAGE_GOALSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2023
{
template <class ContainerAllocator>
struct GoalStatus_
{
  typedef GoalStatus_<ContainerAllocator> Type;

  GoalStatus_()
    : status(0)
    , text()  {
    }
  GoalStatus_(const ContainerAllocator& _alloc)
    : status(0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::assignment_2_2023::GoalStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2023::GoalStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GoalStatus_

typedef ::assignment_2_2023::GoalStatus_<std::allocator<void> > GoalStatus;

typedef boost::shared_ptr< ::assignment_2_2023::GoalStatus > GoalStatusPtr;
typedef boost::shared_ptr< ::assignment_2_2023::GoalStatus const> GoalStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2023::GoalStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2023::GoalStatus_<ContainerAllocator1> & lhs, const ::assignment_2_2023::GoalStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2023::GoalStatus_<ContainerAllocator1> & lhs, const ::assignment_2_2023::GoalStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::GoalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::GoalStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::GoalStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a7ffb7542e8f2c34c310f44cb69496e";
  }

  static const char* value(const ::assignment_2_2023::GoalStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a7ffb7542e8f2c3ULL;
  static const uint64_t static_value2 = 0x4c310f44cb69496eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2023/GoalStatus";
  }

  static const char* value(const ::assignment_2_2023::GoalStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# GoalStatus.msg\n"
"int32 status\n"
"string text\n"
;
  }

  static const char* value(const ::assignment_2_2023::GoalStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2023::GoalStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2023::GoalStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_GOALSTATUS_H
