// Generated by gencpp from file assignment_2_2023/LastTargetResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_LASTTARGETRESPONSE_H
#define ASSIGNMENT_2_2023_MESSAGE_LASTTARGETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2023
{
template <class ContainerAllocator>
struct LastTargetResponse_
{
  typedef LastTargetResponse_<ContainerAllocator> Type;

  LastTargetResponse_()
    : x(0.0)
    , y(0.0)  {
    }
  LastTargetResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LastTargetResponse_

typedef ::assignment_2_2023::LastTargetResponse_<std::allocator<void> > LastTargetResponse;

typedef boost::shared_ptr< ::assignment_2_2023::LastTargetResponse > LastTargetResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2023::LastTargetResponse const> LastTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2023/LastTargetResponse";
  }

  static const char* value(const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LastTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2023::LastTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2023::LastTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_LASTTARGETRESPONSE_H
