// Generated by gencpp from file assignment_2_2023/LastTarget.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_LASTTARGET_H
#define ASSIGNMENT_2_2023_MESSAGE_LASTTARGET_H

#include <ros/service_traits.h>


#include <assignment_2_2023/LastTargetRequest.h>
#include <assignment_2_2023/LastTargetResponse.h>


namespace assignment_2_2023
{

struct LastTarget
{

typedef LastTargetRequest Request;
typedef LastTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LastTarget
} // namespace assignment_2_2023


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2023::LastTarget > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::assignment_2_2023::LastTarget&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2023::LastTarget > {
  static const char* value()
  {
    return "assignment_2_2023/LastTarget";
  }

  static const char* value(const ::assignment_2_2023::LastTarget&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2023::LastTargetRequest> should match
// service_traits::MD5Sum< ::assignment_2_2023::LastTarget >
template<>
struct MD5Sum< ::assignment_2_2023::LastTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::LastTarget >::value();
  }
  static const char* value(const ::assignment_2_2023::LastTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::LastTargetRequest> should match
// service_traits::DataType< ::assignment_2_2023::LastTarget >
template<>
struct DataType< ::assignment_2_2023::LastTargetRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::LastTarget >::value();
  }
  static const char* value(const ::assignment_2_2023::LastTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2023::LastTargetResponse> should match
// service_traits::MD5Sum< ::assignment_2_2023::LastTarget >
template<>
struct MD5Sum< ::assignment_2_2023::LastTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::LastTarget >::value();
  }
  static const char* value(const ::assignment_2_2023::LastTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::LastTargetResponse> should match
// service_traits::DataType< ::assignment_2_2023::LastTarget >
template<>
struct DataType< ::assignment_2_2023::LastTargetResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::LastTarget >::value();
  }
  static const char* value(const ::assignment_2_2023::LastTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_LASTTARGET_H
